FROM rust:1.70-slim as BUILDER
WORKDIR /build/
COPY . ./
RUN cargo build -p gateway --release
  
# TODO: Change to musl + alpine
FROM debian:bullseye-slim
WORKDIR /app/
COPY --from=BUILDER /build/target/release/gateway .
ENV PATH "/app:$PATH"
CMD ["gateway"]
