[package]
name = "headless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firezone-client-connlib = { path = "../../libs/client" }
clap = { version = "4.2", features = ["derive"] }
url = { version = "2.3.1", default-features = false }
tracing-subscriber = { version = "0.3" }
tracing = { version = "0.1" }
