[package]
name = "connlib-apple"
version = "0.1.4"
edition = "2021"

build = "build.rs"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
libc = "0.2"
swift-bridge = "0.1"
firezone-connlib = { path = "../" }

[lib]
name = "connlib"
crate-type = ["staticlib"]
