name: build

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  static_analysis:
    name: Static analysis
    strategy:
      matrix:
        rust: [stable, nightly]
        runs-on:
          - ubuntu-18.04 # Deprecated
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-10.15 # Deprecated
          - macos-11
          - macos-12
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update toolchain
        run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }} && rustup component add clippy
      - name: Run cargo static analysis checks
        run: |
          cargo check
          cargo clippy -- -D clippy::all
          cargo test
