name: build

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  static_analysis:
    name: Static analysis
    strategy:
      matrix:
        rust: [stable, nightly]
        runs-on:
          - ubuntu-18.04 # Deprecated
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-10.15 # Deprecated
          - macos-11
          - macos-12
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Authenticate SSH agent
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.VIRTNET_CLONE_KEY }}
            ${{ secrets.NDISAPI_CLONE_KEY }}
      - name: Run cargo static analysis checks
        run: |
          cargo check
          cargo clippy -- -D clippy::all
          cargo test
