name: build

on:
  pull_request:
  push:
    branches:
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cargo_windows:
    name: Check
    strategy:
      matrix:
        rust: [stable, nightly]
        runs-on:
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update toolchain
        run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Authenticate SSH agent
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.NDISAPI_CLONE_KEY }}'
          ssh-add - <<< '${{ secrets.VIRTNET_CLONE_KEY }}'
      - name: Run cargo check
        run: cargo check
